name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js for image-streamer
      uses: actions/setup-node@v3
      with:
        node-version: '20.10.0'

    - name: Install dependencies for image-streamer
      run: |
        npm install

    - name: Compile TypeScript for image-streamer
      run: |
        npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push image-streamer image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dip-sharing-board-image-streamer:latest -f Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/dip-sharing-board-image-streamer:latest
